name: Release package

on:
  push:
    branches:
      - master

env:
  HUSKY: 0

jobs:
  check:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci --quiet --ignore-scripts

      - name: Audit dependencies
        run: npm audit --omit=dev --audit-level=moderate

      - name: Lint project
        run: npm run lint:project

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - check
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci --quiet --ignore-scripts

      - name: Import GPG key for Finando GitHub Bot
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.FINANDO_GITHUB_BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.FINANDO_GITHUB_BOT_GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: false # https://github.com/semantic-release/semantic-release/pull/1871

      - name: Release
        env:
          GIT_AUTHOR_NAME: ${{ steps.gpg.outputs.name }}
          GIT_AUTHOR_EMAIL: ${{ steps.gpg.outputs.email }}
          GIT_COMMITTER_NAME: ${{ steps.gpg.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ steps.gpg.outputs.email }}
          GITHUB_TOKEN: ${{ secrets.FINANDO_GITHUB_BOT_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.FINANDO_GITHUB_BOT_TOKEN }}
        run: npx semantic-release
